log-filter = "info"

[[peers]]
mode = "nts"
address = "time.cloudflare.com:4460"

[[peers]]
mode = "nts"
address = "nts.sth1.ntp.se:4460"

[[peers]]
mode = "nts"
address = "nts.sth2.ntp.se:4460"

[system]
min-intersection-survivors = 3
panic-threshold = 999
startup-panic-threshold = { forward = 9999, backward = 9999 }
