name: Docker Image

on:
  workflow_dispatch:
  push:
    branches: [ main ]
    paths:
      - 'build/*'
      - 'os/*'
      - 'boot/*'

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
      # - uses: docker/setup-buildx-action@v2
      - uses: azure/docker-login@v1
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
      - uses: actions/checkout@v3
        with:
          fetch-depth: 1
      - run: |
          ./dist.sh
