name: Nginx Docker

on:
  workflow_dispatch:
  push:
    branches: [ main ]
    paths:
      - 'ubuntu/nginx/*'
      - '.github/workflows/nginx.yml'
jobs:

  build:

    runs-on: ubuntu-latest

    steps:
      # - uses: docker/setup-buildx-action@v2
      # - uses: azure/docker-login@v1
      #   with:
      #     username: ${{ secrets.DOCKER_USERNAME }}
      #     password: ${{ secrets.DOCKER_PASSWORD }}
      # - uses: actions/checkout@v3
      #   with:
      #     fetch-depth: 1
      # - run: |
      #     ./dist.sh
      - name: Checkout
        uses: actions/checkout@v3
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v2
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2
      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
      - name: Docker meta
        id: meta
        uses: docker/metadata-action@v4
        with:
          images: ${{secrets.DOCKER_ORG}}/nginx
          flavor: latest=false
          tags: |
            type=sha,prefix={{date 'YYYYMMDD'}}-,format=short
            type=raw,value=latest
      - name: Build and push
        uses: docker/build-push-action@v4
        with:
          context: ubuntu/nginx
          platforms: linux/amd64,linux/arm64
          push: true
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}
          # file: 'Dockerfile'
